default_categories = {
    "Website Feedback": {
        "Navigation Issues": ["I can't find the help pages", "Where are the FAQs?", "Help pages are hard to find"],
        "Missing Product Information": ["Product details are missing", "Can't find product specs", "Information about the product is not available"],
        "Promotion Details": ["Promotion details are unclear", "How do I find current offers?", "Terms and conditions of deals are confusing"],
        "Accessibility Issues": ["Accessibility options are not working", "How do I access the disability options?", "Having trouble with accessibility features"],
        "Contact Options": ["Can't find contact support options", "Support phone number was disconnected", "How do I contact support?"],
        "Order Page Issues": ["Issues with the 'My Orders' page", "Can't return order on the 'My Orders' page", "Problems with the 'My Orders' page"],
        "Pop-Up Feedback": ["Feedback about website pop-ups", "Too many pop-ups", "Pop-ups are annoying"],
        "Search Feature Issues": ["Search feature gives poor results", "Feedback about search functionality", "Trouble finding products using search"],
        "Product Comparison Tool": ["Feedback about the product comparison tool", "No clear way to compare products", "Comparison tool could be improved"],
        "Live Commerce Pop-Up": ["Live commerce pop-up is intrusive", "Feedback about live commerce pop-up"],
        "Design and Navigation": ["Website is hard to navigate", "Banners block information", "Site is not user-friendly"],
    },
    "Performance Issues": {
        "Mobile Website and App": ["Problems with the mobile webpage", "Buggy experiences on mobile", "App is not working properly"],
        "Slow Website": ["Website is slow", "Pages take too long to load", "Experiencing performance issues"],
        "Buggy Performance": ["Website is glitchy", "Finding many issues with the site", "Website is misbehaving"],
        "Geolocation Issues": ["Website did not use my location accurately", "Website thinks I'm in another country", "Inaccurate location detection"]
    },
    "Product Support and Warranty": {
        "Loaner Device Request": ["Need a loaner device for repair", "Can I get a temporary device?", "What to do without a working device?"],
        "Product Registration Issues": ["Issues registering product", "How to register a device?", "Can't register product"],
        "High Repair Costs": ["Repair costs are too high", "Can't afford repair cost", "Repair is too expensive"],
        "Multiple Repair Requests": ["Multiple repair requests needed", "Too many repairs needed", "Why multiple repair requests?"],
        "Out of Warranty": ["Device out of warranty, can't fix", "Can't fix device out of warranty", "Out of warranty issues"],
        "Repair Lost in Transit": ["Repair lost in transit", "Carrier lost my repair", "Lost device during repair shipping"],
        "Care Plan Coverage": ["Questions about care plan coverage", "What's covered by the care plan?", "Benefits of the care plan?"],
        "Troubleshooting Help": ["Need help troubleshooting product", "Troubleshooting steps not working", "Can you help me troubleshoot?"],
        "Unresolved Issues": ["Issues not resolved by support", "Support did not follow up", "Received incorrect troubleshooting"],
        "Repair Work Feedback": ["Repair work was unsatisfactory", "Repair took too long", "Not satisfied with repair"]
    },
    "Return and Refund Issues": {
        "Refund Processing Time": ["Refund processing time too long", "Where's my refund?", "How long to process a refund?"],
        "Return Window Extension": ["Need extension on return window", "More time to send return", "Can I get a return extension?"],
        "Return Shipping Label": ["Need return shipping label", "Help with return label", "Can I get a return label?"],
        "Return to Reorder": ["Wait for return and refund before new order", "Can you expedite my refund for reorder?", "Why wait for refund to place new order?"],
        "Shipping Label Print Requirement": ["Need to print return label", "No printer for return label", "How to return without a printer?"],
        "General Return Policy": ["Explain return policy", "How to return an item?", "Return policy restrictions?"],
        "Wrong Refund Amount": ["Wrong refund amount received", "Incorrect refund amount", "Refund discrepancy"],
        "No Refund Received": ["Return failed, no refund", "Return failed, unsent", "Did not receive refund after return"],
        "Installation Charge Not Refunded": ["Installation charge not refunded", "Refund for installation charge", "Why was installation charge deducted?"],
        "Return Not Available": ["Can't initiate a return", "No return option available", "Why can't I return this?"],
        "Refund Request": ["Want a refund for order", "Can I get a refund?", "Requesting a refund"],
        "Exchange or Replacement": ["Want to exchange product", "Can I get a replacement?", "Requesting an exchange"],
        "Partial Refund": ["Received partial refund", "Partial refund discrepancies", "Didn't get full refund"],
        "Tracking Returned Item": ["Difficulty tracking returned item", "Can't track return", "Return tracking issues"],
        "International Return": ["International return difficulties", "How to return from abroad?", "Can I return from overseas?"],
        "Return Shipping Damage": ["Product damaged during return shipping", "Received damaged return", "Return damaged in transit"],
        "Tax Exception Refund": ["Need tax refund for tax exception", "Requesting tax refund", "Tax refund for exemption"],
        "Return Label Issues": ["Problems with return label", "Error with return label", "Return label not working"]
    },
    "Product Feedback": {
        "Missing Charger": ["Charger not included with order", "Why no charger included?", "Order missing charger"],
        "Product Durability": ["Poor product durability", "Product is flimsy", "Not satisfied with durability"],
        "General Feedback": ["General feedback about product", "Product feedback"],
        "Mobile App Feedback": ["Feedback about mobile apps", "Mobile app issues"],
        "Pre-Installed Apps": ["Feedback about pre-installed apps", "Dislike pre-installed apps"],
        "Missing Headphone/Speaker Port": ["No headphone/speaker port", "Why no headphone jack?", "Missing ports"],
        "Missing Product Parts": ["Product missing parts", "Order missing pieces", "Parts missing from product"]
    },
    "Policy Feedback": {
        "Replacement Policy": ["Frustrated with replacement policy", "Can't replace items"],
        "Device Locking Policies": ["Concerns about device locking policies", "Explain locking policies"],
        "Shipping Policy": ["Critiques about shipping policy", "Feedback about shipping policy"],
        "Return Policy": ["Critiques about return policy", "Return policy feedback"],
        "Payment Methods": ["Accepted payment methods?", "What payment methods available?"],
        "Tax Exception Policy": ["Questions about tax exception policy", "Explain tax exception policy"]
    },
    "Trade-In Issues": {
        "Trade-In Charge": ["Unhappy with trade-in charge", "Charged for trade-in", "Why trade-in charge?"],
        "Trade-In Shipping": ["Sent trade-in but still charged", "Trade-in shipping issues", "Why charge after shipping trade-in?"],
        "Empty Box Charge": ["Charged for empty box trade-in", "Didn't send empty box", "Empty box trade-in charge"],
        "Watch Trade-In Charge": ["Charged for watch trade-in", "Watch trade-in issues"],
        "Cracked Screen Trade-In": ["Charged for cracked screen trade-in", "Cracked screen trade-in issues"],
        "Positive Trade-In Feedback": ["Positive feedback about trade-in program", "Happy with trade-in values"],
        "Trade-In Value Questions": ["Questions about trade-in value", "What's my trade-in worth?"],
        "Trade-In Eligibility": ["Questions about trade-in eligibility", "How to qualify for trade-in?"],
        "Trade-In Discount Issues": ["Trade-in discount changes in cart", "Trade-in credit not reflected in checkout"]
    },
    "Cancelled Orders": {
        "System Cancellation": ["Order cancelled by system", "Why was my order cancelled?", "Order cancelled multiple times"],
        "International Cancellation": ["Order cancelled due to international payment method", "Order cancelled for being outside the US"]
    },
    "Order Management": {
        "Change Delivery Options": ["Can't change delivery options", "Can I change shipping method?"],
        "Cancel Order": ["Can't cancel order", "Unable to cancel order"],
        "Modify Order": ["Can't modify products on order", "Unable to modify order"],
        "Add to Order": ["Can't add product to order", "Unable to add to order"],
        "Modify Payment Method": ["Can't change payment methods", "Unable to modify payment methods"],
        "Cancel to Modify": ["Had to cancel order to make changes", "Why cancel to modify order?"],
        "Customer Cancel Request": ["Want to cancel order", "Requesting order cancellation"]
    },
    "Shipping and Delivery": {
        "Order Not Shipped": ["Order not shipped yet and it's late", "Where is my order?"],
        "Order Status": ["Check order status", "When will order ship?"],
        "Order Shipped, Late": ["Order shipped but it's late", "Where is my shipped order?"],
        "Order Lost in Transit": ["Order lost in transit, no tracking updates", "Where is my order?"],
        "Changing Delivery Date": ["Delivery date keeps changing", "Why is delivery date changing?"],
        "Order Delivered, Not Received": ["Order marked as delivered but not received", "Where is my delivered order?"],
        "Delivery Date Changed": ["Original delivery date changed after order", "Why did delivery date change?"],
        "Missing Product from Shipment": ["Product missing from shipment", "Order missing items"],
        "Wrong Product Received": ["Received wrong product", "Wrong product model/color"],
        "Damaged Product Delivered": ["Product delivered damaged", "Order received damaged"],
        "Custom Product Delivery Delay": ["Custom product delivery delayed", "Why custom order delay?"],
        "In-Store Pickup Issues": ["In-store pickup delayed", "No pick-up confirmation"],
        "Defective Product Delivered": ["Defective product delivered", "Product does not work"],
        "No Tracking Information": ["No tracking information", "Can't track order"],
        "Received Damaged Product": ["Received damaged product", "Product scratched/dented"],
        "Missed Delivery Date": ["Delivery date missed", "Where is my order?"],
        "Inaccurate Delivery Tracking": ["Inaccurate delivery tracking", "Tracking issues"],
        "Delivery Zone Restrictions": ["Can't checkout due to delivery zones", "Shipping restriction issues"],
        "Wrong Delivery Location": ["Order delivered to wrong location", "Wrong delivery address"],
        "Delivery Attempt Failed": ["Delivery attempted but not completed", "Where is my order?"]
    },
    "Customer Service Feedback": {
        "Agent Unable to Solve Issue": ["Agent couldn't resolve issue", "Problem-solving ability lacking"],
        "Long Wait Time": ["Long wait time to connect", "Time to connect too long"],
        "Agent Knowledge": ["Agent knowledge lacking", "Agents need better training"],
        "Promotion Knowledge": ["Agents unaware of promotions", "Agents need promotion training"],
        "Agent Follow-Up": ["Agent did not follow up", "No follow-up from agent"],
        "Technical Issue Resolution Time": ["Technical issue resolution took too long", "Delayed technical problem resolution"],
        "Disconnected Call": ["Call disconnected, no callback", "Chats disconnecting"],
        "Long Hold Time": ["Long hold time during call", "Agent response time too long"],
        "Language Barrier": ["Language barrier with agent", "Difficult to understand agent"],
        "Slow Chat Replies": ["Slow chat responses", "Long response time in chat"],
        "Lack of Empathy": ["Agent lacked empathy", "Didn't feel understood by agent"],
        "Unhelpful Supervisor": ["Supervisor was not helpful", "Unhelpful chat supervisor"],
        "Refused Escalation": ["Agent refused to escalate issue", "Couldn't speak with supervisor"],
        "Switching to Competitor": ["Considering switching to competitor", "Will never buy from here again"],
        "Repeated Troubleshooting": ["Agent repeated ineffective troubleshooting", "Repeated advice not solving issue"],
        "Customer Service Closed": ["Customer service closed, can't contact", "Unable to reach support"],
        "Supervisor Required": ["Need to speak with supervisor", "Requesting supervisor contact"]
    },
    "Checkout Issues": {
        "Payment Issues": ["Payment issue during checkout", "Unable to process payment"],
        "Long Delivery Time": ["Delivery time too long", "Expected delivery time too long"],
        "Carrier Website Issues": ["Unable to log into carrier site for checkout", "Carrier login issues"],
        "Price Changes": ["Price changes during checkout", "Price discrepancy"],
        "Checkout Errors": ["Error messages during checkout", "Unable to complete checkout"],
        "Finance Offer Changes": ["Finance offer changes during checkout", "Financing alterations in cart"],
        "Promotion Issues": ["Promotion not applied", "Promotion questions"],
        "Reward Points Issues": ["Reward points not applied", "Unable to use reward points"],
        "Split Payment Issues": ["Split payment option not working", "Multiple payment options issue"],
        "Technical Checkout Issues": ["Unable to checkout due to technical issue", "Technical problems at checkout"],
        "Reserve Promo Credit Issues": ["Promo credit not applying", "$50 reserve promo issue"],
        "Shipping Issues": ["Shipping address verification issue", "Limited shipping methods"],
        "Carrier Experience": ["Carrier account issues", "Difficult carrier account experience"],
        "Cart Issues": ["Products removed from cart", "Unable to add items to cart"]
    },
    "Installation Issues": {
        "Not Installed": ["Product not installed at delivery", "Installation process requires multiple visits"],
        "Missed Installation Appointment": ["Installers missed appointment", "Where are the installers?"],
        "Late Installers": ["Installers arrived late", "Late installation appointment"],
        "Missing Installation Parts": ["Missing parts for installation", "Installers lacked necessary parts"],
        "Installation Damages": ["Installers damaged product or property", "Installation caused damage"],
        "Rude Installation Staff": ["Rude installation staff", "Poor treatment by installers"],
        "Post-Installation Issues": ["Issues after installation", "Problems with installed product"],
        "Installation Not Done": ["Product not installed during delivery"]
    },
    "Privacy and Security": {
        "Data Security and Privacy": ["Concerns about data security and privacy", "Website data security issues"],
        "Transparency in Data Usage": ["Lack of transparency in data usage", "How is my data used?"],
        "Unknown Charges and Scams": ["Experienced scams and phishing", "Unknown charges or fees"],
        "Payment Information Security": ["Concerns about payment information security", "Payment security issues"],
        "Privacy Settings Issues": ["Issues with privacy settings", "Privacy settings problems"]
    },
    "Account Management": {
        "Login Issues": ["Unable to log into account", "Login problems"],
        "Password Retrieval": ["Can't retrieve lost password", "Password retrieval issues"],
        "Verification Email Issues": ["Didn't receive verification email", "Verification email problems"],
        "Account Info Modification": ["Can't change account information", "Update account details"],
        "Account Deactivation": ["Can't deactivate or delete account", "Want to delete account"],
        "Linking Accounts": ["Difficulty linking multiple accounts", "Linking account issues"],
        "Two-Factor Authentication": ["Two-factor authentication issues", "Can't pass two-factor authentication"],
        "Unwanted Marketing": ["Received unwanted marketing emails", "Unwanted notifications"],
        "Preference Settings": ["Can't set account preferences", "Changing email preferences"]
    },
    "Pre-Order Questions": {
        "Product Details": ["Need product details", "Questions about product features"],
        "Product Availability": ["When will product be available?", "Product out of stock"],
        "International Availability": ["Can I buy this internationally?", "Shipping outside the US"],
        "Product Compatibility": ["Questions about product compatibility", "Do products work together?"]
    },
    "Specific Issue Callouts": {
        "Missing Product Parts": ["Missing product parts", "Parts not included with order"],
        "Discount Feedback": ["Feedback about discounts", "Discount availability"],
        "Color Issues": ["Received wrong color", "Color not as expected"]
    }
}
